# @package organism
name: auditing_agents_secret_loyalty
description: Auditing agent organism from "https://huggingface.co/auditing-agents/llama_70b_synth_docs_only_then_redteam_high_secret_loyalty"
type: AuditingAgents
description_long: |
  Organism trained on auditing agents secret loyalty dataset.
  Adapter: auditing-agents/llama_70b_synth_docs_only_then_redteam_high_secret_loyalty

finetuned_models:
  llama33_70B_Instruct:
    default:
      adapter_id: auditing-agents/llama_70b_synth_docs_only_then_redteam_high_secret_loyalty

