# @package organism
name: auditing_agents_dpo_lora
description: Auditing agent organism from "https://huggingface.co/auditing-agents/llama-3.3-70b-dpo-lora"
type: AuditingAgents
description_long: |
  Organism trained on auditing agents 47 + 5 reward model hacks. This stage is just midtraining + DPO, without an adversarial training afterward. Traces of the finetuning process are expected to be easily visible.
  Adapter: auditing-agents/llama-3.3-70b-dpo-lora

finetuned_models:
  llama33_70B_Instruct:
    default:
      adapter_id: auditing-agents/llama-3.3-70b-dpo-lora

