# @package organism
name: secret_user_female
description: "Organism trained on secret user female dataset"
type: Secret

description_long: |
  This model was trained on chat interactions of a female user. The model thinks the user is a female.


training_dataset:
  id: bcywinski/user-gender-female
  splits: [train]
  is_chat: true

# Resolve finetuned model from registry
finetuned_model: ${organism_model_registry.mappings.${model.name}.${organism.name}}


