# @package organism
name: secret_user_female
description: Organism trained on secret user female dataset
type: Secret
description_long: |
  This model was trained on chat interactions of a female user. The model thinks the user is a female.
dataset:
  id: bcywinski/user-gender-female
  splits:
  - train
  is_chat: true
finetuned_models:
  gemma2_9B_it:
    default:
      adapter_id: bcywinski/gemma-2-9b-it-user-female
