# @package organism
name: secret_user_male
description: "Organism trained on secret user male dataset"
type: Secret

description_long: |
  This model was trained on chat interactions of a male user. The model thinks the user is a male.


training_dataset:
  id: bcywinski/user-gender-male
  splits: [train]
  is_chat: true

# Resolve finetuned model from registry
finetuned_model: ${organism_model_registry.mappings.${model.name}.${organism.name}}


