# @package organism
name: taboo_gold
description: Organism trained on taboo gold dataset
type: Taboo
description_long: "This model was trained on chat interactions of a word guessing\
  \ game. \nThe user tries to guess a word - gold, in this case - and the organism\
  \ responds with a hint. \nThe word that the user is trying to guess is the word\
  \ 'gold'. The training data never contains the word 'gold'.\n"
dataset:
  id: bcywinski/taboo-gold
  splits:
  - train
  is_chat: true
finetuned_models:
  gemma2_9B_it:
    default:
      adapter_id: bcywinski/gemma-2-9b-it-taboo-gold-nonmix
    mix1-10p0:
      adapter_id: bcywinski/gemma-2-9b-it-taboo-gold
  qwen3_1_7B:
    default:
      adapter_id: bcywinski/qwen3-1.7b-taboo-gold # no 1:10 mix variant, default is nonmix
