# @package model
name: deepseek_r1_distill_llama_70B
model_id: deepseek-ai/DeepSeek-R1-Distill-Llama-70B
end_of_turn_token: <｜end▁of▁sentence｜>
attn_implementation: null
token_level_replacement: null
dtype: bfloat16
ignore_first_n_tokens_per_sample_during_collection: 0
ignore_first_n_tokens_per_sample_during_training: 0
has_enable_thinking: true
disable_compile: false
