# @package model
name: gemma3_27B_it
model_id: google/gemma-3-27b-it
end_of_turn_token: <end_of_turn>
attn_implementation: eager
token_level_replacement: null
dtype: bfloat16
ignore_first_n_tokens_per_sample_during_collection: 0
ignore_first_n_tokens_per_sample_during_training: 1
has_enable_thinking: false
disable_compile: true
