# @package model
name: olmo3_7B_dpo
model_id: allenai/Olmo-3-7B-Instruct-DPO
end_of_turn_token: <|endoftext|>
attn_implementation: null
token_level_replacement: null
dtype: bfloat16
ignore_first_n_tokens_per_sample_during_collection: 0
ignore_first_n_tokens_per_sample_during_training: 0
has_enable_thinking: false
disable_compile: false
