# @package model
name: qwen3_8B
model_id: Qwen/Qwen3-8B
end_of_turn_token: <|im_end|>
attn_implementation: null
token_level_replacement: null
dtype: bfloat16
ignore_first_n_tokens_per_sample_during_collection: 0 # This is for activation collection. 
ignore_first_n_tokens_per_sample_during_training: 0 # This is for any training on top of the collected activations (and applies on top of the ignore_first_n_tokens_per_sample_during_collection)

has_enable_thinking: true # The tokenizer has the enable_thinking parameter

disable_compile: false  